config/routes.rb
Rails.application.routes.draw do
  get 'duties/index'
  resources :csv_exports

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :renewals, except: [:destroy] do
    resources :renewal_payments, only: [:create] do
      collection do
        post :process_payment
      end
    end
  end
  root 'renewals#index'

  resources :contents
  resources :duties, only: [:index]

  namespace :admin do
    resources :renewals, only: %i[index show] do
      member do
        patch :soft_delete
        patch :undelete
      end
    end
    resources :boats
    resources :members, only: %i[index show update] do
      member do
        patch :soft_delete
        patch :undelete
      end
      resources :onboarding, only: [:new, :create]
    end
    resources :onboarding, only: [:index, :show, :edit, :update, :destroy] do
      member do
        patch :retry_step
        get :progress
      end
    end
    resources :csv_exports

    root to: 'renewals#index' # <--- Root route
  end

  get '/check.txt', to: proc { [200, {}, ['simple_check']] }

end

app/controllers/admin/renewals_controller.rb
module Admin
  class RenewalsController < Admin::ApplicationController
    include ActionView::Helpers::UrlHelper
    def index
      params[:year] ||= Time.zone.now.year
      @year = if params[:year] == 'all'
                nil
              else
                params[:year].to_i
              end
      @years_collection = ((Date.today.year - 10..Date.today.year).map do |year|
        [year, year]
      end).reverse.unshift(['All', :all])

      respond_to do |format|
        format.html do
          find_renewals
        end
        format.csv do
          find_renewals(paginate: false)
          send_data @renewals.to_csv, filename: "renewals-#{Date.today}.csv"
        end
      end
    end

    def show
      @renewal = Renewal.find(params[:id])
    end

    def soft_delete
      notice = error = nil
      renewal = Renewal.find(params[:id])
      if renewal&.update_attribute(:deleted, true)
        link = undelete_admin_renewal_path(renewal.id, request.query_parameters)
        notice = "Renewal for #{renewal} was successfully deleted. #{button_to('Undo', link, method: :patch,
                                                                                             class: 'text-red-500')}".html_safe
      elsif renewal.present?
        error = "Renewal for #{renewal} could not be deleted: #{renewal.errors.full_messages.to_sentence}"
      else
        error = 'Renewal could not be found.'
      end

      redirect_to admin_renewals_path(request.query_parameters), notice: notice, error: error
    end

    def undelete
      notice = error = nil
      renewal = Renewal.find(params[:id])
      if renewal&.update_attribute(:deleted, false)
        notice = "Renewal for #{renewal} was successfully restored."
      elsif renewal.present?
        error = "Renewal for #{renewal} could not be restored: #{renewal.errors.full_messages.to_sentence}"
      else
        error = 'Renewal could not be found.'
      end

      redirect_to admin_renewals_path(request.query_parameters), notice: notice, error: error
    end

    private

    def find_renewals(paginate: true)
      scope = Renewal.not_deleted
      scope = scope.where("date_part('year', created_at) = ?", @year) if @year.present?
      scope = scope.order('created_at DESC')

      @renewals = if paginate
                    scope.paginate(page: params[:page], per_page: 10)
                  else
                    scope
                  end
    end
  end
end

app/controllers/renewals_controller.rb
class RenewalsController < ApplicationController
  def index
  end

  def new
    @renewal = Renewal.new(membership_class: params[:membership_class])
    @renewal_step_with_override = params[:step]&.to_sym || @renewal.current_step
    populate_renewal
  end

  def edit
    @renewal = find_renewal

    if @renewal.nil?
      flash[:error] = "Sorry, we couldn't find that renewal"
      redirect_to new_renewal_path
      return
    end

    @renewal_step_with_override = params[:step]&.to_sym || @renewal.current_step
    populate_renewal
  end

  def create
    # Check for existing renewal with same primary member email in current year
    primary_member_email = renewal_params.dig(:primary_member_attributes, :email)
    
    if primary_member_email.present?
      existing_renewal = find_existing_renewal_by_email(primary_member_email.downcase.strip)
      
      if existing_renewal.present?
        # Send reminder email and show message
        RenewalNotificationMailer.renewal_reminder(existing_renewal).deliver
        
        flash[:notice] = "You already have a renewal in progress for #{Date.current.year}. We've sent you an email with a link to continue updating your renewal."
        redirect_to new_renewal_path
        return
      end
    end
    
    @renewal = Renewal.new(renewal_params)
    @renewal.generate_token!
    if @renewal.save
      @renewal_step_with_override = params[:step]&.to_sym || @renewal.current_step
      RenewalNotificationMailer.new_renewal_member(@renewal).deliver
      redirect_to edit_renewal_path(@renewal)
    else
      flash[:error] = "There was an error creating the renewal: #{@renewal.errors.full_messages.to_sentence}"
      render :new
      nil
    end
  end

  def update
    find_renewal
    Rails.logger.info "Updating renewal: #{@renewal.email}"
    if @renewal.nil?
      flash[:error] = "Sorry, we couldn't find that renewal"
      redirect_to new_renewal_path
      return
    end

    if @renewal.is_paid?
      flash[:error] =
        %q(Sorry, you can't update a paid renewal. Please contact <a href="mailto:membership@sheffieldviking.org.uk">membership@sheffieldviking.org.uk</a> to discuss any changes.)
      redirect_to renewal_path(@renewal)
      return
    end

    @renewal.generate_reference
    @renewal.update(renewal_params)
    @renewal_step_with_override = params[:step]&.to_sym || @renewal.current_step

    send_email_notitifactions
    if @renewal.valid?
      if @renewal.complete?
        begin
          redirect_to renewal_path(@renewal)
          return
        rescue StandardError => e
          Rails.logger.error e.message
          Rails.logger.error e.class
          Rails.logger.error e.backtrace
        end
      end
    else
      flash[:error] = @renewal.errors.full_messages.to_sentence
    end
    populate_renewal
    if @renewal_step_with_override == :payment
      render :show
    else
      render :edit
    end
  end

  def show
    find_renewal
    if @renewal.nil?
      flash[:error] = "Sorry, we couldn't find that renewal"
      redirect_to new_renewal_path
      return
    end

    if @charge = @renewal.charges.select { |charge| charge.captured? }.first
      @show_payment_link = false # @renewal.payment_id.nil?
    end

    @renewal_step_with_override = params[:step]&.to_sym || @renewal.current_step
    populate_renewal
  end

  private

  def find_existing_renewal_by_email(email)
    # Find existing renewal with matching primary member email in current year
    Renewal.joins(:primary_member)
           .where(members: { email: email, primary: true })
           .where("DATE_PART('year', renewals.created_at) = ?", Date.current.year)
           .not_deleted
           .first
  end

  def send_email_notitifactions
    return unless @renewal.present?
    return unless @renewal.persisted?

    return unless @renewal.complete?

    if @renewal.is_paid?
      # RenewalNotificationMailer.renewal_payment_confirmation(@renewal).deliver
    else
      RenewalNotificationMailer.renewal_payment_pending(@renewal).deliver
    end

    # Note to hook up renewal_paid_by_bank_transfer email here if marked as such.

    # begin
    #   # RenewalNotificationMailer.new_renewal_member(@renewal).deliver
    #   debugger
    #   RenewalNotificationMailer.renewal_payment_confirmation(@renewal).deliver if @renewal.is_paid?
    #   RenewalNotificationMailer.new_renewal_admin(@renewal).deliver
    # rescue StandardError => e
    #   Rails.logger.error e.message
    #   Rails.logger.error e.class
    #   Rails.logger.error e.backtrace
    # end
  end

  def find_renewal
    @renewal = Renewal.find_by(reference: [params[:id], params[:id].gsub('-', '')])
  end

  def renewal_params
    # params.require(:renewal).permit!
    res = params.require(:renewal).permit(
      :membership_class, :email, :address_1, :address_2, :postcode, :no_boats,
      :emergency_contact_details, :comment, :share_data_for_commission, :declaration_confirmed,
      :bank_transfer_payment_reported_at,
      primary_member_attributes: %i[id first_name last_name email phone dob _destroy],
      secondary_members_attributes: %i[id first_name last_name email phone dob _destroy],
      boats_attributes: %i[id berthing is_sailboard classname sail_number hull_colour name insured _destroy],
      duties_attributes: %i[id preference thursday saturday sunday _destroy]
    )

    res[:email] = res[:email].downcase.strip if res[:email].present?
    res[:bank_transfer_payment_reported_at] = Time.now if res[:bank_transfer_payment_reported_at] == 'true'
    res.delete(:boats_attributes) if res[:no_boats] == '1'
    res
  end

  def populate_renewal
    @renewal.build_primary_member if @renewal.primary_member.nil?
    # 4.times { @renewal.secondary_members.build } if @renewal.secondary_members.empty?
    @renewal.secondary_members.build if @renewal.secondary_members.empty?
    @renewal.boats.build if @renewal.boats.empty?
    @renewal.duties.build if @renewal.duties.empty?
  end
end

app/helpers/renewals_helper.rb
module RenewalsHelper
  def duties_calendar_enabled?
    false
  end

  def s(tag, options = {})
    c = Content.where(tag: tag).first
    if current_admin_user.nil? && c.try(:content).nil?
      tag
    elsif current_admin_user.nil?
      c.content.html_safe
    else
      c ||= Content.create(tag: tag)
      return c.content.try(:html_safe) || "[[#{c.tag}]]" if options[:no_link]

      link_to(c.content.try(:html_safe) || "[[#{c.tag}]]",
              "/admin/contents/#{c.id}/edit?modal=true",
              class: 'editable_text',
              # 'data-reveal-id' => "textEditor",
              # 'data-reveal-ajax' => true,
              target: '_blank')
    end
  end

  def mark_required(value)
    'data-required=true' if value
  end

  def sidebar_link(key:, url:, options: {}, scope: nil)
    is_link = @renewal&.persisted?
    is_current_step = (key == @renewal_step_with_override)
    scope ||= [:sidebar]
    link_class = if is_current_step
                   'flex flex-nowrap items-center p-2 text-gray-100 rounded-lg dark:text-white bg-gray-600 dark:bg-gray-300 group'
                 else
                   'flex flex-nowrap items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-200 dark:hover:bg-gray-700 group'
                 end

    ERB.new(<<-HTML).result(binding).html_safe
			<li class="<%= link_class %> <%= 'active' if request.path == '#{url}' %>"
				  data-action="click->sidebar#toggle"
			>
				<%= link_to_if(is_link, I18n.t(key, scope: scope, default: key), url, options) %>
			</li>
    HTML
  end

  def admin_sidebar_link(key:, url:, options: {}, scope: nil)
    scope ||= %i[admin sidebar]
    link_class = if key.to_s == controller.controller_name
                   'flex flex-nowrap items-center p-2 text-gray-100 rounded-lg dark:text-white bg-gray-600 dark:bg-gray-300 group'
                 else
                   'flex flex-nowrap items-center p-2 text-gray-900 rounded-lg dark:text-white hover:bg-gray-200 dark:hover:bg-gray-700 group'
                 end

    ERB.new(<<-HTML).result(binding).html_safe
      <li class="<%= link_class %> <%= 'active' if request.path == '#{url}' %>"
          data-action="click->sidebar#toggle"
      >
        <%= link_to(I18n.t(key, scope: scope, default: key), url, options) %>
      </li>
    HTML
  end

  def renewal_step_title
    path_stem = caller.first.match(%r{/_(\w+).html.erb:})[1]
    # path_stem = File.basename(__FILE__, '.html.erb').gsub(/\A_/, '').to_s
    I18n.t(path_stem, scope: :sidebar)
  end
end

app/views/admin/renewals/_member.html.erb
<div class="member-details">
    <p><strong>Name:</strong> <%= member&.full_name %></p>
    <p><strong>Email:</strong> <%= member&.email %></p>
    <p><strong>Phone:</strong> <%= member&.phone %></p>
    <p><strong>Primary Member?:</strong> <%= member&.primary? %></p>
</div>

app/views/admin/renewals/edit.html.erb
<%= form_with(model: @renewal, local: true, class: "space-y-6") do |form| %>
    <div class="space-y-4">
        <div>
            <%= form.label :renewal_date, class: "block text-sm font-medium text-gray-700" %>
            <%= form.date_field :renewal_date, class: "mt-1 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
        </div>

        <div>
            <%= form.fields_for :primary_member do |primary_member_fields| %>
                <%= primary_member_fields.label :first_name, "Primary Member Name", class: "block text-sm font-medium text-gray-700" %>
                <%= primary_member_fields.text_field :first_name, class: "mt-1 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>

                <%= primary_member_fields.label :last_name, "Primary Member Name", class: "block text-sm font-medium text-gray-700" %>
                <%= primary_member_fields.text_field :last_name, class: "mt-1 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
            <% end %>
        </div>

        <div>
            <%= form.fields_for :secondary_members do |secondary_member_fields| %>
                <%= secondary_member_fields.label :first_name, "Secondary Member Name", class: "block text-sm font-medium text-gray-700" %>
                <%= secondary_member_fields.text_field :first_name, class: "mt-1 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>

                <%= secondary_member_fields.label :last_name, "Secondary Member Name", class: "block text-sm font-medium text-gray-700" %>
                <%= secondary_member_fields.text_field :last_name, class: "mt-1 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
            <% end %>
        </div>

        <div>
            <%= form.fields_for :boats do |boat_fields| %>
                <%= boat_fields.label :name, "Boat Name", class: "block text-sm font-medium text-gray-700" %>
                <%= boat_fields.text_field :name, class: "mt-1 block w-full shadow-sm sm:text-sm border-gray-300 rounded-md" %>
            <% end %>
        </div>
    </div>

    <div class="flex justify-end">
        <%= form.submit "Save Renewal", class: "inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
    </div>
<% end %>

app/views/admin/renewals/index.html.erb
<!-- filepath: /Users/james/Projects/James/svscmembership/app/views/admin/renewals/index.html.erb -->
<h1 class="text-2xl font-bold mb-4">Renewals</h1>

<div class="flex justify-between items-center p-4">
  <%= form_with url: request.path, method: :get, local: true, class: "flex items-center" do %>
    <label for="year" class="mr-2">Filter by Year:</label>
    <%= select_tag :year, options_for_select(@years_collection, @year), class: "border border-gray-300 rounded p-2" %>
    <%= submit_tag 'Filter', class: "ml-2 bg-blue-500 text-white rounded p-2" %>
  <% end %>

  <%= link_to 'Download CSV', admin_renewals_path(format: :csv, year: @year), class: "bg-green-500 text-white rounded p-2" %>
</div>

<% if flash[:notice] %>
  <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative mb-4" role="alert">
    <span class="block sm:inline"><%= flash[:notice] %></span>
  </div>
<% end %>

<% if flash[:error] %>
  <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4" role="alert">
    <span class="block sm:inline"><%= flash[:error] %></span>
  </div>
<% end %>

<table class="min-w-full bg-white border border-gray-200">
  <thead>
    <tr>
      <th class="py-2 px-4 border-b">Primary Member Name</th>
      <th class="py-2 px-4 border-b">Season</th>
      <th class="py-2 px-4 border-b">Reference</th>
      <th class="py-2 px-4 border-b">Email</th>
      <th class="py-2 px-4 border-b">Membership Type</th>
      <th class="py-2 px-4 border-b">Paid</th>
      <th class="py-2 px-4 border-b"></th>
      <th class="py-2 px-4 border-b"></th>
      <th class="py-2 px-4 border-b"></th>
    </tr>
  </thead>
  <tbody>
    <% @renewals.each do |renewal| %>
      <tr>
        <td class="py-2 px-4 border-b"><%= (renewal.primary_member || renewal.secondary_members.first)&.full_name %></td>
        <td class="py-2 px-4 border-b"><%= renewal.created_at.year %></td>
        <td class="py-2 px-4 border-b"><%= renewal.reference %></td>
        <td class="py-2 px-4 border-b"><%= renewal.email %></td>
        <td class="py-2 px-4 border-b"><%= renewal.membership_class %></td>
        <td class="py-2 px-4 border-b"><%= renewal.is_paid? ? 'Yes' : 'No' %></td>
        <td class="py-2 px-4 border-b"><%= link_to :view, admin_renewal_path(renewal.id) %></td>
        <td class="py-2 px-4 border-b">
          <% primary_member = renewal.primary_member || renewal.secondary_members.first %>
          <% if primary_member %>
            <%= link_to 'Onboard', new_admin_member_onboarding_path(primary_member.id), class: "bg-blue-500 text-white px-3 py-1 rounded text-sm" %>
          <% end %>
        </td>
        <td class="py-2 px-4 border-b">
          <%= button_to 'Delete', soft_delete_admin_renewal_path(renewal.id, request.query_parameters), method: :patch, data: { confirm: 'Are you sure?' }, class: "text-red-500" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="mt-4">
  <%= will_paginate @renewals %>
</div>

app/views/admin/renewals/show.html.erb
<div class="container mx-auto p-4">
    <div class="bg-white shadow-md rounded-lg p-6">
        <h1 class="text-2xl font-bold mb-4">Renewal Details</h1>
        
        <div class="mb-4">
            <h2 class="text-xl font-semibold">Renewal Information</h2>
            <p><strong>ID:</strong> <%= @renewal.id %></p>

            <p><strong>Created At:</strong> <%= @renewal.created_at.strftime("%B %d, %Y") %></p>
            <p><strong>Updated At:</strong> <%= @renewal.updated_at.strftime("%B %d, %Y") %></p>
        </div>

        <div class="mb-4">
            <h2 class="text-xl font-semibold">Associated Members</h2>
            <%= render "member", member: @renewal.primary_member %>
        </div>

        <div class="mb-4">
            <h2 class="text-xl font-semibold">Payment Details</h2>
            <% @renewal.line_item_rows.each do |row| %>
                <p><%= row.first %>: <%= number_to_currency(row.second, unit: "£") %></p>
            <% end %>
            <p><strong>Total:</strong> <%= number_to_currency(@renewal.total_cost, unit: "£") %></p>
            
            <p class="mt-5"><strong>Card Payment Date:</strong> <%= @renewal.card_payment_date&.strftime("%B %d, %Y") %></p>
            <p><strong>Bank Transfer Date:</strong> <%= @renewal.bank_transfer_payment_reported_at&.strftime("%B %d, %Y") %></p>
        </div>

        <div class="mt-6">
            <%= link_to 'Back', admin_renewals_path, class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
        </div>
    </div>
</div>