config/routes.rb
Rails.application.routes.draw do
  get 'duties/index'
  resources :csv_exports

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :renewals, except: [:destroy] do
    resources :renewal_payments, only: [:create] do
      collection do
        post :process_payment
      end
    end
  end
  root 'renewals#index'

  resources :contents
  resources :duties, only: [:index]

  namespace :admin do
    resources :renewals, only: %i[index show] do
      member do
        patch :soft_delete
        patch :undelete
      end
    end
    resources :boats
    resources :members, only: %i[index show update] do
      member do
        patch :soft_delete
        patch :undelete
      end
      resources :onboarding, only: [:new, :create]
    end
    resources :onboarding, only: [:index, :show, :edit, :update, :destroy] do
      member do
        patch :retry_step
        get :progress
      end
    end
    resources :csv_exports

    root to: 'renewals#index' # <--- Root route
  end

  get '/check.txt', to: proc { [200, {}, ['simple_check']] }

end

app/models/admin/csv_export.rb
module Admin
	class CsvExport < ApplicationRecord
	end
end

app/models/csv_export.rb
class CsvExport < ApplicationRecord

	belongs_to :user

	before_create :populate

	def populate
		case self.export_type
		when 'renewal'
			self.content = renewals_content
		when 'duties'
			self.content = duties_content
		when 'duty_invites'
			self.content = duty_invites_content
		end

	end

	def filename
		"svsc_#{export_type}_#{year}.csv"
	end

	def entry_count
		self.content.count("\n") - 1
	end

	def duty_invites_content
		Renewal.by_year(self.year).to_csv(spreadsheet_columns: :duty_invite_columns)
	end

	def renewals_content
		Renewal.by_year(self.year).to_csv()
	end

	def duties_content
		year = self.year
		duties_by_date = Duty.includes(renewal: [:primary_member]).
			by_year(year).
			order(thursday: :asc, saturday: :asc, sunday: :asc).
			select(:id, :renewal_id, :thursday, :saturday, :sunday, :preference).
			all.group_by{|d| d.end_date}

		out = ""
		duties_by_date.map do |date, duties|
			out << date.strftime("w/e %a #{date.day.ordinalize} %b")
			out << "\n"
			out << duties.map{|duty| %Q[#{duty.preference},#{duty.renewal.all_members.map(&:full_name).uniq.join(' & ')}] }.join("\n")
			out << "\n\n\n"
		end

		out
	end
end

app/controllers/admin/csv_exports_controller.rb
module Admin
  class CsvExportsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/csv_exports_controller.rb
class CsvExportsController < ApplicationController
  include Clearance::Controller
  before_action :require_login
  before_action :set_csv_export, only: [:show, :edit, :update, :destroy]

  # GET /csv_exports
  def index
    @csv_exports = CsvExport.order(created_at: :desc)
  end

  # GET /csv_exports/1
  def show
    respond_to do |format|
      format.html
      format.csv { send_data @csv_export.content, filename: @csv_export.filename, type: Mime::Type.lookup("text/csv"), disposition: 'attachment'}
    end
  end

  # GET /csv_exports/new
  def new
    @csv_export = CsvExport.new(year: Date.today.year)
  end

  # GET /csv_exports/1/edit
  def edit
  end

  # POST /csv_exports
  def create
    @csv_export = CsvExport.new(csv_export_params.merge(user_id: current_user.id))

    if @csv_export.save
      redirect_to csv_exports_path, notice: 'Csv export was successfully created.'
    else
      render :new
    end
  end

  # DELETE /csv_exports/1
  def destroy
    @csv_export.destroy
    redirect_to csv_exports_url, notice: 'Csv export was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_csv_export
      @csv_export = CsvExport.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def csv_export_params
      params.require(:csv_export).permit(:year, :content, :user_id, :export_type)
    end
end

app/helpers/csv_exports_helper.rb
module CsvExportsHelper
end

app/views/csv_exports/_form.html.erb
<%= form_with(model: @csv_export, local: true) do |form| %>
  <% if @csv_export.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(csv_export.errors.count, "error") %> prohibited this csv_export from being saved:</h2>

      <ul>
      <% @csv_export.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div class="field">
    <%= form.label :export_type %>
    <%= form.select :export_type, [['Renewal', 'renewal'], ['Duties', 'duties'], ['Duty Invites', 'duty_invites']] %>
  </div>

  <div class="actions">
    <%= form.submit 'Create', class: 'button' %>
  </div>
<% end %>

app/views/csv_exports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Csv Exports</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Year</th>
      <th>Entries</th>
      <th>Requested by</th>
      <th>Created at</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @csv_exports.each do |csv_export| %>
      <tr>
        <td><%= csv_export.export_type.humanize %></td>
        <td><%= csv_export.year %></td>
        <td><%= csv_export.entry_count %></td>
        <td><%= csv_export.user.email %></td>
        <td><%= csv_export.created_at.strftime("#{csv_export.created_at.day.ordinalize} %B %Y (%H:%M)") %></td>
        <td><%= link_to 'Download', csv_export_path(csv_export.id, format: 'csv') %></td>
        <td><%= link_to 'Delete', csv_export, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Csv Export', new_csv_export_path, class: 'button' %>

app/views/csv_exports/new.html.erb
<div class="row">
  <div class="large-12 columns">
		<h1>New Csv Export</h1>
  </div>
  <div class="large-4 columns">
		<%= render partial: 'form', csv_export: @csv_export %>
  </div>
  <div class="large-12 columns">
		<%= link_to 'Back', csv_exports_path %>
  </div>
</div>

app/views/csv_exports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @csv_export.year %>
</p>


<%= link_to 'Download', csv_export_path(@csv_export, format: :csv) %> |
<%= link_to 'Back', csv_exports_path %>