config/routes.rb
Rails.application.routes.draw do
  get 'duties/index'
  resources :csv_exports

  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  resources :renewals, except: [:destroy] do
    resources :renewal_payments, only: [:create] do
      collection do
        post :process_payment
      end
    end
  end
  root 'renewals#index'

  resources :contents
  resources :duties, only: [:index]

  namespace :admin do
    resources :renewals, only: %i[index show] do
      member do
        patch :soft_delete
        patch :undelete
      end
    end
    resources :boats
    resources :members, only: %i[index show update] do
      member do
        patch :soft_delete
        patch :undelete
      end
      resources :onboarding, only: [:new, :create]
    end
    resources :onboarding, only: [:index, :show, :edit, :update, :destroy] do
      member do
        patch :retry_step
        get :progress
      end
    end
    resources :csv_exports

    root to: 'renewals#index' # <--- Root route
  end

  get '/check.txt', to: proc { [200, {}, ['simple_check']] }

end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this
# `Administrate::ApplicationController`, making it the ideal place to put
# authentication logic or other before_actions.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < ApplicationController
    include Clearance::Controller
    before_action :require_login

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :ensure_canonical_domain

  private

  def ensure_canonical_domain
    return unless Rails.env.production?

    canonical_domain = 'membership.sheffieldviking.org.uk'
    return unless request.host != canonical_domain

    redirect_to "#{request.protocol}#{canonical_domain}#{request.fullpath}", status: :found
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def current_admin_user
		nil
	end
end

app/views/admin/application/_sidebar.html.erb
<div class="h-full px-3 py-4 overflow-y-auto bg-gray-50 dark:bg-gray-800">
    <ul class="space-y-2 font-medium">
        <%= admin_sidebar_link key: :renewals, url: admin_renewals_path(year: params[:year]) %>
        <%= admin_sidebar_link key: :members, url: admin_members_path(year: params[:year]) %>
    </ul>
</div>

app/views/admin/application/stylesheet.html.erb
<%#
# Stylesheet Partial

This partial imports the necessary stylesheets on each page.
By default, it includes the application CSS,
but each page can define additional CSS sources
by providing a `content_for(:stylesheet)` block.
%>

<% Administrate::Engine.stylesheets.each do |css_path| %>
  <%= binding.pry; stylesheet_link_tag css_path %>
<% end %>

<%= yield :stylesheet %>